name: Deploy to 
'on': 
 push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.USER }}'
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          timeout: 30s
          script: |
            pwd
            sudo apt-get update
            sudo apt-get install node.js -y
            node -v
            sudo apt-get install npm -y
            npm --version
            sudo apt-get install ca-certificates curl gnupg
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugi
            sudo docker run hello-world
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /bin/kind
            kind create cluster
            kind create cluster --name=mycluster
            kubectl get nodes
            cd /home/ubuntu/myrepository/
            git pull
            kubectl apply -f deployment.yaml
            kubectl get deploy
